name: Create Service

on:
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: open-pix
    steps:
      - name: creating app service
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 177.93.128.55
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          command_timeout: 2m
          script: |  
            cd /home/ubuntu/api/deploy-openpix/
            cat <<EOF > openpix.service
            [Unit]
            Description=Openpix Service
            [Service]
            User=ubuntu
            # The configuration file application.properties should be here:

            #change this to your workspace
            WorkingDirectory=/home/ubuntu/api/deploy-openpix/openpix/target

            #path to executable. 
            ExecStart=java -jar /home/ubuntu/api/deploy-openpix/openpix/target/openpix-0.0.1-SNAPSHOT.jar

            SuccessExitStatus=143
            TimeoutStopSec=10
            Restart=on-failure
            RestartSec=5

            [Install]
            WantedBy=multi-user.target
            EOF
            sudo cp openpix.service /etc/systemd/system/openpix.service
            sudo systemctl daemon-reload
            sudo systemctl enable openpix.service
            echo "servico criado com sucesso!"
